[package]
name = "kumbull_macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros"
repository = "https://github.com/Juxhinb7/kumbull_macros"
license = "MIT"


[dependencies]
syn = { version = "2.0.106", features = ["full"] }
quote = "1.0.40"

[lib]
proc-macro = true